name: check-pr-label
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
permissions:
  contents: read

jobs:
  check-pr-label:
    name: check-pr-label
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/check-pr-label.yaml@rewrite_workflows_for_community_usage
    with:
      label: "community-approved"
