name: ossf-scorecard
on:
  push:
    branches: [ "main" ]
permissions: read-all

jobs:
  ossf-scorecard:
    name: ossf-scorecard
    permissions:
      security-events: write
      id-token: write
    uses: mindbuttergold/github-actions-reusable-workflows/.github/workflows/ossf-scorecard.yaml@rewrite_workflows_for_community_usage
